# conda env create -f environment.yml
# conda env update --file environment.yml --prune
# conda remove -n 575_proj --all
name: 575_proj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r requirements.txt