# conda env create -f environment.yml
# conda env update --file environment.yml --prune
# conda remove -n product-search-rag --all
name: product-search-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r requirements.txt